name: bilibili-deploy-test

on:
  workflow_dispatch: # 手动触发

jobs:
  deploy-bilibili-tool:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Run Deploy
        timeout-minutes: ${{secrets.TIMEOUT_MINUTES || 15}} # 超时时间(分钟)
        uses: docker://catlair/bilitools-deploy:test
        with: 
          env: 
            BILI_CONFIG="${{ secrets.BILI_CONFIG }}"
            TENCENT_SECRET_ID="${{ secrets.TENCENT_SECRET_ID }}"
            TENCENT_SECRET_KEY="${{ secrets.TENCENT_SECRET_KEY }}"
            RUN_SCF_ALL=y
         tty: true
          
